//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWARDSPENALTIESTYPES
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> PARENT { get; set; }
        public Nullable<int> RIGHTLVL { get; set; }
        public Nullable<short> APKIND { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public Nullable<short> CALCRULE { get; set; }
        public Nullable<double> VALUERATIO { get; set; }
        public Nullable<short> MEASUREUNIT { get; set; }
        public Nullable<decimal> APMAXVALUE { get; set; }
        public Nullable<decimal> APMINLIMIT { get; set; }
        public Nullable<decimal> APMAXLIMIT { get; set; }
        public Nullable<int> ROUNDRULE { get; set; }
        public Nullable<int> APMINTIMELIMIT { get; set; }
        public Nullable<int> APMAXTIMELIMIT { get; set; }
        public Nullable<int> OBJECTKIND { get; set; }
        public Nullable<int> OBJECTID1 { get; set; }
        public Nullable<int> OBJECTID2 { get; set; }
        public Nullable<int> OBJECTID3 { get; set; }
        public string RECSTAMP { get; set; }
        public Nullable<int> CALCINTERVAL { get; set; }
    }
}
