//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bd_nomenclature
    {
<<<<<<< HEAD
=======
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
>>>>>>> origin/master
        public bd_nomenclature()
        {
            this.bd_order = new HashSet<bd_order>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int category_id { get; set; }
        public int vendor_id { get; set; }
<<<<<<< HEAD
        public int measurement_id { get; set; }
=======
        public byte measurement_id { get; set; }
>>>>>>> origin/master
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual bd_category bd_category { get; set; }
        public virtual bd_measurement bd_measurement { get; set; }
        public virtual bd_vendor bd_vendor { get; set; }
<<<<<<< HEAD
=======
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
>>>>>>> origin/master
        public virtual ICollection<bd_order> bd_order { get; set; }
    }
}
