//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bd_subdivision
    {
        public bd_subdivision()
        {
            this.bd_employee = new HashSet<bd_employee>();
            this.bd_reclamation = new HashSet<bd_reclamation>();
            this.bd_rests = new HashSet<bd_rests>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<int> organization_id { get; set; }
    
        public virtual ICollection<bd_employee> bd_employee { get; set; }
        public virtual bd_organization bd_organization { get; set; }
        public virtual ICollection<bd_reclamation> bd_reclamation { get; set; }
        public virtual ICollection<bd_rests> bd_rests { get; set; }
    }
}
