//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bd_vendor
    {
        public bd_vendor()
        {
            this.bd_nomenclature = new HashSet<bd_nomenclature>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string phones { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
    
        public virtual ICollection<bd_nomenclature> bd_nomenclature { get; set; }
    }
}
