//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD_CARDS
    {
        public long CARD_CODE { get; set; }
        public Nullable<long> PEOPLE_ID { get; set; }
        public Nullable<long> OWNER_ID { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<System.DateTime> OFFERED { get; set; }
        public Nullable<System.DateTime> EXP_DATE { get; set; }
        public Nullable<decimal> PIN { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public Nullable<short> DELETED { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string LOCK_REASON { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string TEXT_PASSWORD { get; set; }
        public string CARRIER_DATA { get; set; }
        public System.Guid GUID { get; set; }
        public System.Guid TRANSACT_GUID { get; set; }
    }
}
