//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD_TRANSACTION_NOTES
    {
        public Nullable<long> TRANSACTION_ID { get; set; }
        public Nullable<int> TRANSFER_REASON_ID { get; set; }
        public Nullable<int> AUTH_CODE { get; set; }
        public Nullable<System.DateTime> AUTH_EXP_DATE { get; set; }
        public string NOTES { get; set; }
        public string DOP_INFO { get; set; }
        public System.Guid GUID { get; set; }
        public System.Guid TRANSACT_GUID { get; set; }
    
        public virtual CARD_TRANSACTIONS CARD_TRANSACTIONS { get; set; }
    }
}
