//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHGROUPS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public string NETNAME { get; set; }
        public Nullable<short> ONLINE { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<long> LASTDATARECEIVED { get; set; }
        public Nullable<short> NEEDBACKUP { get; set; }
        public string BACKUPPATH { get; set; }
        public Nullable<int> BACKUPCOPIESQNT { get; set; }
        public Nullable<int> BACKUPSHIFTQNT { get; set; }
        public Nullable<int> BACKUPTIMEOUT { get; set; }
        public Nullable<int> BACKUPTRANSACTIONQNT { get; set; }
        public Nullable<int> RESTAURANT { get; set; }
        public Nullable<int> KEYNUMBER { get; set; }
        public string LICENSE { get; set; }
        public Nullable<int> LICSTATIONS { get; set; }
        public Nullable<System.DateTime> LICEXPIREAT { get; set; }
        public string PDALICENSE { get; set; }
        public Nullable<int> PDALICSTATIONS { get; set; }
        public Nullable<System.DateTime> PDALICEXPIREAT { get; set; }
        public Nullable<int> LICHARDKEYN { get; set; }
        public Nullable<int> LICENSEVERN { get; set; }
        public string PRINTLOGPATH { get; set; }
        public string TIMESYNCNETNAME { get; set; }
        public Nullable<int> LASTGLOBALSHIFT { get; set; }
        public Nullable<short> FTPGETAVAIL { get; set; }
        public string FTPBINDADDR { get; set; }
        public Nullable<int> FTPDATAPORT { get; set; }
        public Nullable<int> FTPINFOPORT { get; set; }
        public Nullable<int> HTTPSERVPORT { get; set; }
        public string HTTPBINDADDR { get; set; }
        public Nullable<short> HTTPGETAVAIL { get; set; }
        public Nullable<int> ONLINEDATAEXPORTPERIOD { get; set; }
        public Nullable<short> SYNCSTATESFLAGS { get; set; }
        public Nullable<long> SERVEREXISTSSINCE { get; set; }
        public Nullable<int> HTTPWEBPRIVILEGE { get; set; }
        public Nullable<int> HTTPAPIPRIVILEGE { get; set; }
        public Nullable<int> HTTPXMLPRIVILEGE { get; set; }
        public string RECSTAMP { get; set; }
    }
}
