//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHMANZREPORTS
    {
        public System.Guid GUID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<System.Guid> RESGUID { get; set; }
        public Nullable<System.Guid> CREATORGUID { get; set; }
        public Nullable<System.Guid> DEVICEGUID { get; set; }
        public Nullable<System.Guid> CASHSTATIONGUID { get; set; }
        public Nullable<System.Guid> BANKGUID { get; set; }
        public Nullable<int> REPORTNUM { get; set; }
        public Nullable<decimal> STARTCOUNTER { get; set; }
        public Nullable<decimal> ENDCOUNTER { get; set; }
        public Nullable<decimal> TOTALRECEIPTS { get; set; }
        public Nullable<decimal> CASH { get; set; }
        public Nullable<decimal> CARDS { get; set; }
        public Nullable<decimal> OTHER { get; set; }
        public Nullable<decimal> RETURNS { get; set; }
        public Nullable<decimal> ADVANCES { get; set; }
        public Nullable<decimal> PROCEEDS { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<System.DateTime> SHIFTDATE { get; set; }
        public Nullable<int> MIDSERVER { get; set; }
        public Nullable<int> SHIFTNUM { get; set; }
        public Nullable<int> ZREPORTID { get; set; }
        public Nullable<short> DELETED { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.Guid> TRANSACT_GUID { get; set; }
    }
}
