//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHES
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public string NETNAME { get; set; }
        public Nullable<int> CASHGROUP { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> RIGHTLVL { get; set; }
        public Nullable<short> RESOLUTION { get; set; }
        public Nullable<short> COLORS { get; set; }
        public Nullable<int> DEFHALLPLANID { get; set; }
        public byte[] RIGHTS { get; set; }
        public Nullable<short> OSTYPE { get; set; }
        public Nullable<short> STTYPE { get; set; }
        public string DEVICENAME { get; set; }
        public string FILEMANAGERPATH { get; set; }
        public Nullable<short> GRAPHICPARAMETERS { get; set; }
        public Nullable<short> SHUTDOWNCASH { get; set; }
        public Nullable<short> AFTERSHIFTCLOSURE { get; set; }
        public Nullable<short> SYNCSTATESFLAGS { get; set; }
        public string RECSTAMP { get; set; }
    }
}
