//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHMANZREPORTTAXES
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> TAXGUID { get; set; }
        public Nullable<System.Guid> ZREPORTGUID { get; set; }
        public Nullable<decimal> VALUE { get; set; }
        public Nullable<System.Guid> TRANSACT_GUID { get; set; }
    }
}
