//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHMANCORRGROUPS
    {
        public System.Guid GUID { get; set; }
        public string NAME { get; set; }
        public Nullable<short> STOCK { get; set; }
        public Nullable<System.Guid> TYPEGUID { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<System.Guid> TRANSACT_GUID { get; set; }
    }
}
