//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHINOUT
    {
        public int MIDSERVER { get; set; }
        public int UNI { get; set; }
        public Nullable<short> ISDEPOSIT { get; set; }
        public Nullable<int> ISTATION { get; set; }
        public Nullable<int> ICOMMONSHIFT { get; set; }
        public Nullable<int> ISHIFT { get; set; }
        public Nullable<int> IDRAWERSHIFT { get; set; }
        public Nullable<int> SIFR { get; set; }
        public Nullable<decimal> ORIGINALSUM { get; set; }
        public Nullable<long> NATIONALSUM { get; set; }
        public Nullable<decimal> REALORIGINALSUM { get; set; }
        public Nullable<int> ICASHIER { get; set; }
        public Nullable<int> IPRINTER { get; set; }
        public Nullable<int> KIND { get; set; }
        public Nullable<int> IDRAWER { get; set; }
        public string EXTFISCID { get; set; }
        public Nullable<int> PRINTNUMBER { get; set; }
        public Nullable<int> IFISCSHIFT { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public Nullable<int> INTFID { get; set; }
        public string CARDCODE { get; set; }
        public Nullable<int> ACCOUNTIDENT { get; set; }
        public Nullable<int> IREASON { get; set; }
        public string OPENREASONNAME { get; set; }
        public Nullable<int> IAUTHOR { get; set; }
        public string TRANSACT_GUID { get; set; }
        public string PAYGUIDSTRING { get; set; }
    }
}
