//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMSended
    {
        public int id { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime LastUpdateDateTime { get; set; }
        public string Email { get; set; }
        public int Status { get; set; }
        public string MailSubject { get; set; }
        public string MailBody { get; set; }
    }
}
