//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMSegment
    {
        public int id { get; set; }
        public string SegmentName { get; set; }
        public string SegmentDescription { get; set; }
        public string SegmentQuery { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string Creator { get; set; }
        public bool IsActive { get; set; }
    }
}
