//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENCIES
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<int> PARENT { get; set; }
        public Nullable<int> RATECLASS { get; set; }
        public Nullable<short> ROUNDRULE { get; set; }
        public Nullable<short> ROUNDMETHOD { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public Nullable<int> GROUP { get; set; }
        public byte[] LIMITDISHES { get; set; }
        public string FORMAT { get; set; }
        public Nullable<int> MINTERFACE { get; set; }
        public Nullable<short> RIGHTLVL { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        public Nullable<int> TAXPAYTYPE { get; set; }
        public Nullable<int> VISUALTYPE_IMAGE { get; set; }
        public Nullable<int> VISUALTYPE_BCOLOR { get; set; }
        public Nullable<int> VISUALTYPE_TEXTCOLOR { get; set; }
        public Nullable<short> VISUALTYPE_FLAGS { get; set; }
        public Nullable<short> SALESTERMS_FLAG { get; set; }
        public Nullable<System.DateTime> SALESTERMS_STARTSALE { get; set; }
        public Nullable<System.DateTime> SALESTERMS_STOPSALE { get; set; }
        public Nullable<int> TIPCHARGE { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> FISCREGPAYTYPE1 { get; set; }
        public Nullable<int> FISCREGPAYTYPE2 { get; set; }
        public Nullable<int> FISCREGPAYTYPE3 { get; set; }
        public Nullable<short> FISCREGUNFISCTYPE { get; set; }
        public Nullable<int> EXTCODE { get; set; }
        public Nullable<int> EXTRESTID { get; set; }
        public string EXTRAINFOCAPTION { get; set; }
        public Nullable<int> MAGNCARDTYPE { get; set; }
        public Nullable<short> FCPAYTRANSACTION { get; set; }
        public Nullable<int> FCSUBACCOUNT { get; set; }
        public Nullable<double> MAXPERCENT { get; set; }
        public Nullable<double> USEBONUSPERCENT { get; set; }
        public Nullable<int> AUTOFILLMODE { get; set; }
        public Nullable<int> AUTHPURPOSE { get; set; }
        public string RECSTAMP { get; set; }
        public Nullable<int> FORENCASHMENT { get; set; }
    }
}
