//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_shcr_Goods
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> server_guid { get; set; }
        public string hash { get; set; }
        public Nullable<short> Deleted { get; set; }
        public Nullable<System.DateTime> dateinsert { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> Parent_RID { get; set; }
        public string Name { get; set; }
        public string Code_Prefix { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> measure_rid { get; set; }
        public string measure_name { get; set; }
        public Nullable<int> Main_Cat_RID { get; set; }
        public Nullable<int> Acc_Cat_RID { get; set; }
        public Nullable<double> Purchase_NDS { get; set; }
        public Nullable<double> Purchase_NSP { get; set; }
        public Nullable<double> Sell_NDS { get; set; }
        public Nullable<double> Sell_NSP { get; set; }
        public Nullable<double> Sell_price_thousand { get; set; }
        public Nullable<int> Ext_Info { get; set; }
        public Nullable<int> Options { get; set; }
        public Nullable<double> Purchase_price { get; set; }
        public Nullable<int> Cm_RID { get; set; }
        public string Cm_Name { get; set; }
        public string Cm_Prefix { get; set; }
        public Nullable<int> Cm_Code { get; set; }
        public Nullable<int> tgMUnitRec_Rid { get; set; }
        public string tgMUnitRec_Name { get; set; }
    }
}
