//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_shcr_doc
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> server_guid { get; set; }
        public Nullable<System.DateTime> dateinsert { get; set; }
        public Nullable<int> doc_rid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string code_text { get; set; }
        public Nullable<int> code_num { get; set; }
        public Nullable<int> options { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> low_stamp { get; set; }
        public Nullable<int> distr_rid { get; set; }
        public string distr_name { get; set; }
        public Nullable<int> receiver_rid { get; set; }
        public string receiver_name { get; set; }
        public Nullable<int> releaser_rid { get; set; }
        public string releaser_name { get; set; }
        public Nullable<int> operation_rid { get; set; }
        public string operation_name { get; set; }
        public string note { get; set; }
        public string header_attr { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_time { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public Nullable<int> edit_time { get; set; }
        public Nullable<System.DateTime> active_doc_date_min { get; set; }
        public string create_user { get; set; }
        public string edit_user { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<int> itype { get; set; }
        public string iprefix { get; set; }
        public Nullable<int> inumb { get; set; }
        public Nullable<System.DateTime> idate { get; set; }
        public Nullable<int> acceptor_rid { get; set; }
        public string acceptor_name { get; set; }
        public Nullable<int> curr_rid { get; set; }
        public Nullable<double> curr_base { get; set; }
        public Nullable<double> curr_doc { get; set; }
        public string curr_code { get; set; }
    }
}
