//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_shcr_CatFoodCost
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> server_guid { get; set; }
        public Nullable<System.DateTime> dateinsert { get; set; }
        public Nullable<System.Guid> ds_guid { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<int> Categ_Ref { get; set; }
        public string Categ_Name { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Brak { get; set; }
        public Nullable<decimal> Sale { get; set; }
        public Nullable<decimal> Inv { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> FoodCost { get; set; }
        public Nullable<decimal> pCost { get; set; }
        public Nullable<decimal> pBreak { get; set; }
        public Nullable<decimal> pInv { get; set; }
        public Nullable<short> type { get; set; }
    }
}
