//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Department1 = new HashSet<Department>();
            this.DepartmentPolicy = new HashSet<DepartmentPolicy>();
            this.DepartmentPosition = new HashSet<DepartmentPosition>();
            this.DepartmentSchedule = new HashSet<DepartmentSchedule>();
            this.DepartmentStaff = new HashSet<DepartmentStaff>();
            this.EmployeeDepartmentSecurityRole = new HashSet<EmployeeDepartmentSecurityRole>();
            this.StaffSchedule = new HashSet<StaffSchedule>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<int> Type { get; set; }
        public string LegalAddress { get; set; }
        public string PhysicalAddress { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Url { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> DepartmentHeadId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public string Number { get; set; }
        public long SequenceValue { get; set; }
    
        public virtual ICollection<Department> Department1 { get; set; }
        public virtual Department Department2 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<DepartmentPolicy> DepartmentPolicy { get; set; }
        public virtual ICollection<DepartmentPosition> DepartmentPosition { get; set; }
        public virtual ICollection<DepartmentSchedule> DepartmentSchedule { get; set; }
        public virtual ICollection<DepartmentStaff> DepartmentStaff { get; set; }
        public virtual ICollection<EmployeeDepartmentSecurityRole> EmployeeDepartmentSecurityRole { get; set; }
        public virtual ICollection<StaffSchedule> StaffSchedule { get; set; }
    }
}
