//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICES
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<int> DEVICETYPE { get; set; }
        public Nullable<int> STATION { get; set; }
        public string MODULE { get; set; }
        public Nullable<int> MODULEIDENT { get; set; }
        public Nullable<int> MODULENUM { get; set; }
        public Nullable<int> BRIGADE { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> LPCLASSIFICATION { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public Nullable<short> UCSPRESET { get; set; }
        public Nullable<int> MINVERSION { get; set; }
        public Nullable<int> AUTOSERVPOSITION { get; set; }
        public string DEFINTFDLL { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public Nullable<int> DOSERDEVICE { get; set; }
        public string MAXPAYTEXTFORMAT { get; set; }
        public string CSCLINKININAME { get; set; }
        public string CSCLINKLOGIN { get; set; }
        public string CSCLINKPASSWORD { get; set; }
        public string CURRENCIESORDER { get; set; }
        public Nullable<int> RECEIPTXMLSCRIPT { get; set; }
        public Nullable<short> NONFISCALONLY { get; set; }
        public Nullable<short> ALWAYSCLOSESHIFT { get; set; }
        public string RECSTAMP { get; set; }
        public string DISHXMLATTRS { get; set; }
    }
}
