//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNTS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<int> PARENT { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public Nullable<short> MODE { get; set; }
        public Nullable<decimal> MAXAMOUNT { get; set; }
        public Nullable<double> MAXPERCENT { get; set; }
        public Nullable<int> COUNTTYPE { get; set; }
        public Nullable<int> CLASSIFICATION { get; set; }
        public Nullable<int> TAXDISHTYPE { get; set; }
        public Nullable<int> MINTERFACE { get; set; }
        public Nullable<short> RIGHTLVL { get; set; }
        public Nullable<short> ROUNDRULE { get; set; }
        public Nullable<int> MAGNCARDTYPE { get; set; }
        public Nullable<int> VISUALTYPE_IMAGE { get; set; }
        public Nullable<int> VISUALTYPE_BCOLOR { get; set; }
        public Nullable<int> VISUALTYPE_TEXTCOLOR { get; set; }
        public Nullable<short> VISUALTYPE_FLAGS { get; set; }
        public Nullable<short> SALESTERMS_FLAG { get; set; }
        public Nullable<System.DateTime> SALESTERMS_STARTSALE { get; set; }
        public Nullable<System.DateTime> SALESTERMS_STOPSALE { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> EXTCODE { get; set; }
        public Nullable<int> EXTRESTID { get; set; }
        public Nullable<short> TRANSACTIONCODE { get; set; }
        public Nullable<decimal> TRANSACTIONVALUE { get; set; }
        public Nullable<short> DISCOUNTDISTRMODE { get; set; }
        public Nullable<short> SURPLUSDISTRMODE { get; set; }
        public Nullable<decimal> MINORDERREST { get; set; }
        public Nullable<short> FISCALOUTSIDE { get; set; }
        public string RECSTAMP { get; set; }
    }
}
