//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISHVOIDS
    {
        public int VISIT { get; set; }
        public int MIDSERVER { get; set; }
        public Nullable<int> ORDERIDENT { get; set; }
        public Nullable<int> DISHUNI { get; set; }
        public Nullable<int> SORTORDER { get; set; }
        public int UNI { get; set; }
        public Nullable<int> SIFR { get; set; }
        public Nullable<int> ICREATOR { get; set; }
        public Nullable<int> IAUTHOR { get; set; }
        public Nullable<int> ICREATORROLE { get; set; }
        public Nullable<int> IAUTHORROLE { get; set; }
        public Nullable<int> SESSIONUNI { get; set; }
        public Nullable<int> VOIDSESSIONUNI { get; set; }
        public Nullable<int> COMBOVOIDUNI { get; set; }
        public string OPENNAME { get; set; }
        public Nullable<double> PIECES { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<decimal> PRLISTSUM { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public string GLOBALIDENT { get; set; }
        public Nullable<short> PRINTED { get; set; }
        public Nullable<long> SAVEDATETIME { get; set; }
        public Nullable<short> STOREDINFM { get; set; }
        public Nullable<short> AFTERBILLUNDO { get; set; }
        public string GUIDSTRING { get; set; }
        public string TRANSACT_GUID { get; set; }
    }
}
