//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public string DATASOURCENAME { get; set; }
        public Nullable<short> ISFISCAL { get; set; }
        public Nullable<short> ISREPORT { get; set; }
        public Nullable<short> UCSPRESET { get; set; }
        public Nullable<int> DOCUMENT { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> MINMAKVERSION { get; set; }
        public Nullable<int> FISCFLAGMASK { get; set; }
        public string RECSTAMP { get; set; }
    }
}
