//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTBASECONFIGS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> UCSPRESET { get; set; }
        public Nullable<short> EDITRIGHT { get; set; }
        public string DBSQLCLASS { get; set; }
        public Nullable<int> SQLTIMEOUT { get; set; }
        public string BASEPARAMS { get; set; }
        public string BATCHDELIM { get; set; }
        public byte[] SQLTYPEMAP { get; set; }
        public byte[] SQLMAXSIZES { get; set; }
        public byte[] SQLVALUEMAP { get; set; }
        public byte[] SQLDBSCRIPT { get; set; }
        public Nullable<int> FIELDNAMESZ { get; set; }
        public string QUALIFIERCH { get; set; }
        public string DATETIMEFMT { get; set; }
        public Nullable<short> UPCASENAMES { get; set; }
        public Nullable<short> FORBIDINT64 { get; set; }
        public Nullable<short> USEASYNCSQL { get; set; }
        public Nullable<int> BASEDONCONF { get; set; }
        public string SERVERROLES { get; set; }
        public string DATABASEROLES { get; set; }
        public byte[] SQLDIMSPLITMAP { get; set; }
        public byte[] SQLCONNINIT { get; set; }
        public byte[] SQLCUBEDATAFORMAT { get; set; }
        public byte[] SQLREPSDATAFORMAT { get; set; }
        public string SQLTIMECONVERSION { get; set; }
        public string SQLTIMEWITHOUTSEC { get; set; }
        public Nullable<int> FASTCOPYDATASIZE { get; set; }
        public string BCPPATH { get; set; }
        public string SQLCASECONVERSION { get; set; }
        public byte[] SQLDATEPARTKIND { get; set; }
        public Nullable<int> BASEDIALECT { get; set; }
        public string RECSTAMP { get; set; }
    }
}
