//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIAS_ADDRESS_OBJECTS
    {
        public long ADDRESS_OBJECT_ID { get; set; }
        public Nullable<System.Guid> AOGUID { get; set; }
        public Nullable<System.Guid> AOID { get; set; }
        public Nullable<short> DELETED { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<short> AOLEVEL { get; set; }
        public Nullable<long> PARENT_ID { get; set; }
        public Nullable<int> POPULARITY { get; set; }
        public System.Guid GUID { get; set; }
        public System.Guid TRANSACT_GUID { get; set; }
        public string FORMALNAME { get; set; }
        public string REGIONCODE { get; set; }
        public string POSTALCODE { get; set; }
        public string SHORTNAME { get; set; }
    }
}
