//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILTERS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> FILTERTYPE { get; set; }
        public Nullable<int> PARENTOBJECT { get; set; }
        public Nullable<int> MOBJECT { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public Nullable<short> FILTER_LANG { get; set; }
        public Nullable<int> FILTER_FLAGS { get; set; }
        public Nullable<int> FILTER_COT { get; set; }
        public Nullable<int> FILTER_UOT { get; set; }
        public Nullable<int> FILTER_EMPLOYEE { get; set; }
        public Nullable<int> FILTER_PERIOD { get; set; }
        public Nullable<int> FILTER_STATION { get; set; }
        public Nullable<int> FILTER_TRADEGROUP { get; set; }
        public Nullable<int> FILTER_DEFAULTER { get; set; }
        public Nullable<int> FILTER_ROLE { get; set; }
        public Nullable<int> FILTER_TABLE { get; set; }
        public Nullable<short> FILTER_COLORS { get; set; }
        public Nullable<int> FILTER_TABLEGROUP { get; set; }
        public Nullable<int> FILTER_GUESTTYPE { get; set; }
        public Nullable<int> FILTER_HALLPLAN { get; set; }
        public Nullable<int> FILTER_EMPLOYEEGROUP { get; set; }
        public Nullable<int> FILTER_BRIGADE { get; set; }
        public Nullable<int> FILTER_RESTAURANT { get; set; }
        public Nullable<System.DateTime> FILTER_STARTAT { get; set; }
        public Nullable<System.DateTime> FILTER_STOPAT { get; set; }
        public Nullable<int> FILTER_CASHGROUP { get; set; }
        public Nullable<int> FILTER_CONCEPT { get; set; }
        public Nullable<int> FILTER_REGION { get; set; }
        public Nullable<int> FILTER_FRANCHISE { get; set; }
        public string RECSTAMP { get; set; }
        public Nullable<int> FILTER_KURS { get; set; }
    }
}
