//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCTIONKEYS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<int> PARENT { get; set; }
        public Nullable<short> FLAGS { get; set; }
        public Nullable<short> UCSPRESET { get; set; }
        public Nullable<int> FOPERATION { get; set; }
        public Nullable<int> FPARAMETER { get; set; }
        public Nullable<int> EOPERATION { get; set; }
        public Nullable<int> EPARAMETER { get; set; }
        public Nullable<short> HIDEIFNORIGHTS { get; set; }
        public byte[] SLCTTYPES { get; set; }
        public Nullable<int> VISUALTYPE_IMAGE { get; set; }
        public Nullable<int> VISUALTYPE_BCOLOR { get; set; }
        public Nullable<int> VISUALTYPE_TEXTCOLOR { get; set; }
        public Nullable<short> VISUALTYPE_FLAGS { get; set; }
        public Nullable<short> STATUS { get; set; }
        public string RECSTAMP { get; set; }
    }
}
