//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERATEDPROPDATAS
    {
        public int SIFR { get; set; }
        public Nullable<int> RKTYPEIDENT { get; set; }
        public Nullable<short> OBJECTREFNO { get; set; }
        public Nullable<int> OBJECTIDENT { get; set; }
        public string PROPERTYVAL { get; set; }
        public string RECSTAMP { get; set; }
    }
}
