//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestVisit
    {
        public System.Guid Id { get; set; }
        public System.Guid CardId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime VisitEnd { get; set; }
        public System.DateTime VisitStart { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public int SequenceValue { get; set; }
        public Nullable<System.Guid> EndEmployeeId { get; set; }
        public System.Guid StartEmployeeId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public string IdentityDocument { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
