//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMSSALED
    {
        public int RESTAURANT { get; set; }
        public byte[] DISHES { get; set; }
        public Nullable<int> BLEN_DISHES { get; set; }
        public byte[] MODIFIERS { get; set; }
        public Nullable<int> BLEN_MODIFIERS { get; set; }
        public string TRANSACT_GUID { get; set; }
    }
}
