//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAKETS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<int> DOCUMENT { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public Nullable<short> UCSPRESET { get; set; }
        public Nullable<short> RIGHTLVL { get; set; }
        public byte[] MAKET { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> WIDTH { get; set; }
        public Nullable<int> INTFISCREGFLAGS { get; set; }
        public Nullable<int> MAKVERSION { get; set; }
        public string RECSTAMP { get; set; }
    }
}
