//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAKETSCHEMEDETAILS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> PARENT { get; set; }
        public Nullable<int> MAKET { get; set; }
        public Nullable<int> XMLMAKET { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public byte[] REPPARAMS { get; set; }
        public Nullable<int> VISUALTYPE_IMAGE { get; set; }
        public Nullable<int> VISUALTYPE_BCOLOR { get; set; }
        public Nullable<int> VISUALTYPE_TEXTCOLOR { get; set; }
        public Nullable<short> VISUALTYPE_FLAGS { get; set; }
        public Nullable<int> CODE { get; set; }
        public Nullable<int> MAINPRINTERPURPOSE { get; set; }
        public Nullable<int> RSRVPRINTERPURPOSE { get; set; }
        public Nullable<int> XMLPRINTERPURPOSE { get; set; }
        public Nullable<int> NFMAKET { get; set; }
        public Nullable<int> NFMAINPRINTERPURPOSE { get; set; }
        public Nullable<int> NFRSRVPRINTERPURPOSE { get; set; }
        public Nullable<short> FIXEDHEIGHT { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public Nullable<int> MAKET2 { get; set; }
        public Nullable<int> MAKET3 { get; set; }
        public Nullable<int> MAKET4 { get; set; }
        public Nullable<int> MAKET5 { get; set; }
        public Nullable<int> MAKET6 { get; set; }
        public Nullable<int> MAKET7 { get; set; }
        public Nullable<int> MAKET8 { get; set; }
        public Nullable<int> MAKET9 { get; set; }
        public Nullable<int> MAKET10 { get; set; }
        public Nullable<short> COPIES { get; set; }
        public string RECSTAMP { get; set; }
    }
}
