//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MB_DISHDISCOUNT
    {
        public int CODE { get; set; }
        public string GUIDSTRING { get; set; }
        public int ITEMORDER { get; set; }
        public string BOARD { get; set; }
        public string NAME { get; set; }
        public string STARTDISCOUNT { get; set; }
    }
}
