//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MB_SCREENS
    {
        public string GUIDSTRING { get; set; }
        public string BOARD { get; set; }
        public string NAME { get; set; }
        public int ITEMORDER { get; set; }
        public int WIDTH { get; set; }
        public int HEIGHT { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int ISADVERT { get; set; }
        public string HEADERPIC { get; set; }
        public Nullable<int> HEADERX { get; set; }
        public Nullable<int> HEADERY { get; set; }
        public Nullable<int> HEADERWIDTH { get; set; }
        public Nullable<int> HEADERHEIGHT { get; set; }
    }
}
