//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mc_task
    {
        public mc_task()
        {
            this.mc_extra = new HashSet<mc_extra>();
            this.mc_userTask = new HashSet<mc_userTask>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string username { get; set; }
        public System.DateTime dt { get; set; }
    
        public virtual ICollection<mc_extra> mc_extra { get; set; }
        public virtual ICollection<mc_userTask> mc_userTask { get; set; }
    }
}
