//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENUITEMS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public string SHORTNAME { get; set; }
        public string ALTSHORTNAME { get; set; }
        public Nullable<double> PORTIONWEIGHT { get; set; }
        public string PORTIONNAME { get; set; }
        public string ALTPORTION { get; set; }
        public Nullable<int> KURS { get; set; }
        public Nullable<short> QNTDECDIGITS { get; set; }
        public Nullable<int> MODISCHEME { get; set; }
        public Nullable<short> MODIWEIGHT { get; set; }
        public Nullable<int> TAXDISHTYPE { get; set; }
        public Nullable<short> COOKMINS { get; set; }
        public string COMMENT { get; set; }
        public byte[] INSTRUCT { get; set; }
        public Nullable<short> FLAGS { get; set; }
        public Nullable<int> SCALECOEF { get; set; }
        public Nullable<double> TARAWEIGHT { get; set; }
        public Nullable<double> CONFIRMQNT { get; set; }
        public Nullable<double> MINRESTQNT { get; set; }
        public Nullable<int> VISUALTYPE_IMAGE { get; set; }
        public Nullable<int> VISUALTYPE_BCOLOR { get; set; }
        public Nullable<int> VISUALTYPE_TEXTCOLOR { get; set; }
        public Nullable<short> VISUALTYPE_FLAGS { get; set; }
        public Nullable<short> SALESTERMS_FLAG { get; set; }
        public Nullable<System.DateTime> SALESTERMS_STARTSALE { get; set; }
        public Nullable<System.DateTime> SALESTERMS_STOPSALE { get; set; }
        public Nullable<int> MINTERFACE { get; set; }
        public Nullable<int> PARENT { get; set; }
        public Nullable<int> TOPARENTCATEG { get; set; }
        public Nullable<short> RIGHTLVL { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> EXTCODE { get; set; }
        public Nullable<int> EXTRESTID { get; set; }
        public Nullable<short> SALEOBJECTTYPE { get; set; }
        public Nullable<short> RATETYPE { get; set; }
        public Nullable<int> ROUNDTIME { get; set; }
        public Nullable<int> MINIMUMTARIFTIME { get; set; }
        public Nullable<int> MAXIMUMTARIFTIME { get; set; }
        public Nullable<int> IGNOREDTARIFTIME { get; set; }
        public Nullable<int> DEFTARIFTIMELIMIT { get; set; }
        public Nullable<decimal> MINTARIFAMOUNT { get; set; }
        public Nullable<decimal> MAXTARIFAMOUNT { get; set; }
        public Nullable<short> TARIFFROUNDRULE { get; set; }
        public Nullable<short> MONEYROUNDRULE { get; set; }
        public Nullable<int> COMBOSPLITMODE { get; set; }
        public Nullable<int> COMBOJOINMODE { get; set; }
        public Nullable<int> ADDLINEMODE { get; set; }
        public Nullable<int> COMBODISCOUNT { get; set; }
        public Nullable<int> CHANGETOCOMBO { get; set; }
        public byte[] LARGEIMAGEPATH { get; set; }
        public Nullable<decimal> GUESTSDISHRATING { get; set; }
        public string RECSTAMP { get; set; }
    }
}
