//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGES
    {
        public int IDENT { get; set; }
        public Nullable<int> IEMPLOYEE { get; set; }
        public Nullable<int> IAUTHOR { get; set; }
        public Nullable<System.DateTime> EXPIREDATE { get; set; }
        public string TEXT { get; set; }
        public Nullable<int> MESSAGETYPE { get; set; }
        public Nullable<int> PARAMETER { get; set; }
        public Nullable<int> FROMSTATION { get; set; }
        public Nullable<System.DateTime> ADDEDAT { get; set; }
        public Nullable<int> REPEATCOUNT { get; set; }
        public string TRANSACT_GUID { get; set; }
    }
}
