//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODISCHEMEDETAILS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> MODISCHEME { get; set; }
        public Nullable<int> MODIGROUP { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public Nullable<int> SORTNUM { get; set; }
        public Nullable<short> UPLIMIT { get; set; }
        public Nullable<short> DOWNLIMIT { get; set; }
        public Nullable<int> DEFAULTMODIFIER { get; set; }
        public Nullable<double> SHQUANTITY { get; set; }
        public Nullable<short> FREECOUNT { get; set; }
        public Nullable<int> EXTCODE { get; set; }
        public Nullable<int> EXTRESTID { get; set; }
        public string RECSTAMP { get; set; }
    }
}
