//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occupation
    {
        public Occupation()
        {
            this.OccupationPolicy = new HashSet<OccupationPolicy>();
            this.OccupationSchedule = new HashSet<OccupationSchedule>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.Guid DepartmentPositionId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> Rate { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public long SequenceValue { get; set; }
    
        public virtual DepartmentPosition DepartmentPosition { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<OccupationPolicy> OccupationPolicy { get; set; }
        public virtual ICollection<OccupationSchedule> OccupationSchedule { get; set; }
    }
}
