//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATIONS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<int> PARENT { get; set; }
        public Nullable<short> FRIGHT { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public Nullable<int> MINTERFACE { get; set; }
        public Nullable<short> UCSPRESET { get; set; }
        public Nullable<int> IMAGEINDEX { get; set; }
        public string DESCRIPTION { get; set; }
        public string ALTDESCRIPTION { get; set; }
        public string COMMENT { get; set; }
        public string ALTCOMMENT { get; set; }
        public string OPERATION { get; set; }
        public Nullable<int> LINKEDSCRIPT { get; set; }
        public Nullable<int> EXTRACONFIRMATION { get; set; }
        public string RECSTAMP { get; set; }
    }
}
