//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_taskChecklist
    {
        public int id { get; set; }
        public int TaskID { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public bool Checked { get; set; }
        public Nullable<System.DateTime> StartDT { get; set; }
        public Nullable<System.DateTime> EndDT { get; set; }
        public Nullable<System.DateTime> CheckDT { get; set; }
    
        public virtual p_task p_task { get; set; }
    }
}
