//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETEREXCEPTIONS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> PARAMETER { get; set; }
        public Nullable<int> SHORTVALUE { get; set; }
        public string STRINGVALUE { get; set; }
        public string ALTSTRINGVALUE { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> EDITRIGHT { get; set; }
        public string RECSTAMP { get; set; }
    }
}
