//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLG_IR_REPORTS
    {
        public string GUIDSTRING { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<short> REPTYPE { get; set; }
        public byte[] LAYOUT { get; set; }
        public Nullable<short> UCSPRESET { get; set; }
        public Nullable<short> STATUS { get; set; }
        public string REPGROUP_GUID { get; set; }
        public Nullable<short> IR_USERACTIONS { get; set; }
        public Nullable<System.Guid> TRANSACT_GUID { get; set; }
        public Nullable<int> BEGIN_GROUP { get; set; }
        public Nullable<int> VISIBLE { get; set; }
        public string IR_EDITRIGHT { get; set; }
        public Nullable<int> USE_AS_WEB { get; set; }
        public string IRREPORT_PARENT_GUID { get; set; }
        public string VER { get; set; }
        public string REPNUM { get; set; }
    }
}
