//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLG_IR_LINKCONFIGDETAIL
    {
        public string GUIDSTRING { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public string SOURCEPARAMETER { get; set; }
        public string GRIDREPORTPARAMNAME { get; set; }
        public Nullable<short> UCSPRESET { get; set; }
        public string IR_LINKCONFIG_GUID { get; set; }
        public string SOURCEFIELD_GUID { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<System.Guid> TRANSACT_GUID { get; set; }
    }
}
