//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICEFORMULAS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> PRICETYPE { get; set; }
        public Nullable<short> SCOPE { get; set; }
        public Nullable<int> FILTER { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public byte[] FORMULA { get; set; }
        public Nullable<decimal> FIXED { get; set; }
        public Nullable<short> DEFAULT { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public string RECSTAMP { get; set; }
    }
}
