//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICES
    {
        public int SIFR { get; set; }
        public Nullable<int> OBJECTID { get; set; }
        public Nullable<short> SPECIES { get; set; }
        public Nullable<int> PRICETYPE { get; set; }
        public Nullable<int> MODIFIERS { get; set; }
        public Nullable<decimal> VALUE { get; set; }
        public string RECSTAMP { get; set; }
    }
}
