//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFLINKS
    {
        public short TABLE { get; set; }
        public short NUMINTABLE { get; set; }
        public string GUIDSTRING { get; set; }
        public string TABLENAMES { get; set; }
        public Nullable<short> LINKTABLE { get; set; }
        public string LINKNAMES { get; set; }
        public string LINKALIAS { get; set; }
        public string LINKITEMDATACLASS { get; set; }
        public Nullable<short> FOREIGNKEY { get; set; }
        public string RECSTAMP { get; set; }
    }
}
