//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFRESOURCES
    {
        public int SIFR { get; set; }
        public string RESNAME { get; set; }
        public byte[] DATA { get; set; }
        public Nullable<int> BLST_VARDATA { get; set; }
        public string RECSTAMP { get; set; }
    }
}
