//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFTABLES
    {
        public short SIFR { get; set; }
        public string NAME { get; set; }
        public string TABLENAME { get; set; }
        public Nullable<short> GENERATOR { get; set; }
        public Nullable<short> TRADEOBJ { get; set; }
        public Nullable<short> NODELETION { get; set; }
        public Nullable<short> SELECTACT { get; set; }
        public Nullable<short> UPDATEACT { get; set; }
        public Nullable<short> DELETEACT { get; set; }
        public Nullable<short> CHILDACT { get; set; }
        public string XMLMASK { get; set; }
        public Nullable<short> XMLEXPORT { get; set; }
        public string RECSTAMP { get; set; }
    }
}
