//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTINGSERVERS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> UCSPRESET { get; set; }
        public string NETWORKNAME { get; set; }
        public Nullable<short> CUBEBUILDER { get; set; }
        public Nullable<short> DATASYNCHER { get; set; }
        public Nullable<int> MINETIMEOUT { get; set; }
        public Nullable<short> CUBESSOURCE { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public string LICENSE { get; set; }
        public Nullable<int> LICHARDINFO { get; set; }
        public Nullable<System.DateTime> LICEXPIREAT { get; set; }
        public Nullable<int> LICENSEKEYN { get; set; }
        public Nullable<int> LICHARDKEYN { get; set; }
        public Nullable<int> LICSTATIONS { get; set; }
        public Nullable<int> LICENSEVERN { get; set; }
        public Nullable<int> EXTBASECONF { get; set; }
        public string EXTBASENAME { get; set; }
        public string EXTBASEPASS { get; set; }
        public Nullable<int> LOGGINGTYPE { get; set; }
        public Nullable<int> CUBETIMEOUT { get; set; }
        public byte[] ITEMSRIGHTS { get; set; }
        public Nullable<short> FTPGETAVAIL { get; set; }
        public string FTPBINDADDR { get; set; }
        public Nullable<int> FTPDATAPORT { get; set; }
        public Nullable<int> FTPINFOPORT { get; set; }
        public Nullable<int> HTTPSERVPORT { get; set; }
        public string HTTPBINDADDR { get; set; }
        public Nullable<short> HTTPGETAVAIL { get; set; }
        public Nullable<int> XMLSERVPORT { get; set; }
        public string XMLCRYPTKEY { get; set; }
        public string XMLFILESPATH { get; set; }
        public string XMLDEBUGPATH { get; set; }
        public Nullable<int> WEBREPSPORT { get; set; }
        public string WEBREPSPATH { get; set; }
        public string EXECUTEDATA { get; set; }
        public Nullable<short> UDBMINETYPE { get; set; }
        public string FASTREPORTSERVERPATH { get; set; }
        public Nullable<int> ONLINEDATAEXPORTPERIOD { get; set; }
        public Nullable<int> ONLINEDATATRANSFERPERIOD { get; set; }
        public Nullable<int> ONLINEMAXFILESPROCESS { get; set; }
        public Nullable<short> SYNCSTATESFLAGS { get; set; }
        public Nullable<int> HANDLESRESTAURANTS { get; set; }
        public Nullable<int> HTTPWEBPRIVILEGE { get; set; }
        public Nullable<int> HTTPAPIPRIVILEGE { get; set; }
        public Nullable<int> HTTPXMLPRIVILEGE { get; set; }
        public string RECSTAMP { get; set; }
        public Nullable<int> LICHARDINFONEW { get; set; }
    }
}
