//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<int> GCEXTCODE { get; set; }
        public Nullable<int> CREATEBASIS { get; set; }
        public byte[] RIGHTS { get; set; }
        public byte[] OPRIGHTS { get; set; }
        public byte[] PRIVILEGES { get; set; }
        public byte[] REPORTS { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> EDITRIGHT { get; set; }
        public Nullable<int> RESTAURANT { get; set; }
        public Nullable<int> EXTBASECONF { get; set; }
        public string SQLUSERNAME { get; set; }
        public string SQLPASSWORD { get; set; }
        public string RECSTAMP { get; set; }
    }
}
