//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPL8_TRANSACT
    {
        public int ID_INC { get; set; }
        public System.Guid GUID { get; set; }
        public System.Guid SERVER_GUID { get; set; }
        public Nullable<System.DateTime> DTS { get; set; }
    }
}
