//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_DATABASES
    {
        public int Database_ID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Connection_Type { get; set; }
        public string SC_Address { get; set; }
        public Nullable<int> SC_Port { get; set; }
        public string SC_Host { get; set; }
        public string Server_Guid { get; set; }
        public string Server_Name { get; set; }
        public string SC_Intercept_Guid { get; set; }
        public string SC_Intercept_Name { get; set; }
        public string DC_Computer_Name { get; set; }
        public Nullable<int> SHC_Parent_Connection_ID { get; set; }
        public string SHC_Child_Name { get; set; }
        public Nullable<short> Deleted { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string IB_User_Name { get; set; }
        public string IB_Password { get; set; }
        public Nullable<short> IB_SQL_Dialect { get; set; }
        public string IB_Char_Set { get; set; }
        public string IB_Database { get; set; }
        public string Oracle_User_Name { get; set; }
        public string Oracle_Password { get; set; }
        public string Oracle_Database { get; set; }
        public string MSSQL_Connection_String { get; set; }
    }
}
