//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_CUBE_DIMENSION_MODS
    {
        public int Dimension_Mod_ID { get; set; }
        public Nullable<int> Cube_Dimension_ID { get; set; }
        public string Caption { get; set; }
        public Nullable<short> Dim_Modifier { get; set; }
        public Nullable<short> Dim_Axis { get; set; }
        public string Format { get; set; }
        public Nullable<short> Deleted { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<int> Dim_Flags { get; set; }
        public Nullable<short> Order_No { get; set; }
        public string Field_Name { get; set; }
    }
}
