//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_CUBE_FACTS
    {
        public int Cube_Fact_ID { get; set; }
        public Nullable<int> Report_ID { get; set; }
        public string Fact_Name { get; set; }
        public string Caption { get; set; }
        public string Format { get; set; }
        public Nullable<short> Deleted { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<short> Order_No { get; set; }
        public Nullable<short> PreGroup_ID { get; set; }
        public string Formula { get; set; }
        public Nullable<int> Flags { get; set; }
        public Nullable<int> Modifier { get; set; }
        public string Src_Name { get; set; }
    }
}
