//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT_STORED_REPORTS
    {
        public int Stored_Report_ID { get; set; }
        public Nullable<int> Report_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Filter_Values { get; set; }
        public Nullable<int> Filter_ID { get; set; }
        public Nullable<int> Template_ID { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
        public Nullable<System.DateTime> Date_Start_Work { get; set; }
        public Nullable<System.DateTime> Date_End_Work { get; set; }
        public Nullable<System.DateTime> Date_Cancel { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<int> Database_ID { get; set; }
        public string E_Mail { get; set; }
        public Nullable<short> E_Mail_Action { get; set; }
        public string Export_Formats { get; set; }
        public string Location_On_Server { get; set; }
        public Nullable<int> Disk_Size { get; set; }
        public string Messages_Text { get; set; }
        public Nullable<short> Have_Errors { get; set; }
        public Nullable<short> Deleted { get; set; }
        public string Report_Values { get; set; }
        public string Filter_Params { get; set; }
        public Nullable<short> Shedule_Type { get; set; }
        public Nullable<System.DateTime> Time_Begin { get; set; }
        public Nullable<System.DateTime> Date_Begin { get; set; }
        public Nullable<short> Day_Mask { get; set; }
        public Nullable<short> Month_Mask { get; set; }
        public Nullable<short> Month_Day { get; set; }
        public Nullable<int> Flags { get; set; }
        public Nullable<System.DateTime> Shedule_Next_Time { get; set; }
    }
}
