//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sb_managers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sb_managers()
        {
            this.sb_problems = new HashSet<sb_problems>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int rights { get; set; }
        public Nullable<int> restaurant_id { get; set; }
        public string domain_name { get; set; }
    
        public virtual sb_restaurants sb_restaurants { get; set; }
        public virtual sb_rights sb_rights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sb_problems> sb_problems { get; set; }
    }
}
