//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sb_top
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string problem { get; set; }
        public int restaurant_id { get; set; }
        public string solution { get; set; }
    
        public virtual sb_restaurants sb_restaurants { get; set; }
    }
}
