//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SBEntities_F : DbContext
    {
        public SBEntities_F()
            : base("name=SBEntities_F")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sb_managers> sb_managers { get; set; }
        public virtual DbSet<sb_problems> sb_problems { get; set; }
        public virtual DbSet<sb_restaurants> sb_restaurants { get; set; }
        public virtual DbSet<sb_rights> sb_rights { get; set; }
    }
}
