//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULEDREPORTS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> SCHEDULEDREPORT { get; set; }
        public Nullable<int> REPORTINGSERVER { get; set; }
        public byte[] FILTERDATAVALUE { get; set; }
        public byte[] FILTWHERECLAUSE { get; set; }
        public Nullable<int> SCHEDULEDPERIOD { get; set; }
        public Nullable<int> CALCULATEPERIOD { get; set; }
        public Nullable<System.DateTime> FILTERDATEFROM { get; set; }
        public Nullable<System.DateTime> FILTERDATETILL { get; set; }
        public byte[] FILTERUSERTEXT { get; set; }
        public Nullable<int> FIXEDDATE { get; set; }
        public string RECSTAMP { get; set; }
    }
}
