//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICECHECKS
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<short> FLAGS { get; set; }
        public Nullable<int> PARENT { get; set; }
        public Nullable<int> ORDERNUM { get; set; }
        public Nullable<int> GROUPSIFR { get; set; }
        public byte[] PRINTGROUPS { get; set; }
        public Nullable<int> PRINTER { get; set; }
        public Nullable<int> RESERVPRINTER { get; set; }
        public Nullable<int> XMLPRINTER { get; set; }
        public Nullable<int> MAKET { get; set; }
        public Nullable<int> REMINDMAKET { get; set; }
        public Nullable<int> VOIDMAKET { get; set; }
        public Nullable<int> WEIGHTMAKET { get; set; }
        public Nullable<int> TRANSFERMAKET { get; set; }
        public Nullable<short> BOTHPRINTTYPE { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> SERVICEPRINTMODE { get; set; }
        public string RECSTAMP { get; set; }
    }
}
