//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmsMessageStatus
    {
        public System.Guid Id { get; set; }
        public int Provider { get; set; }
        public string Phone { get; set; }
        public string Message { get; set; }
        public Nullable<System.Guid> IdPerson { get; set; }
        public string FullName { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public string EventTitle { get; set; }
        public System.DateTime EnqueueDate { get; set; }
        public string EqueueId { get; set; }
        public Nullable<decimal> EqueueCharge { get; set; }
        public int DeliveryStatus { get; set; }
        public string DeliveryError { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public long SequenceValue { get; set; }
    }
}
