//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_RK7_SHIFTS_VOIDS
    {
        public System.Guid GLOBALSHIFTGUID { get; set; }
        public Nullable<System.Guid> RESTAURANTGUID { get; set; }
        public Nullable<System.Guid> MIDSERVERGUID { get; set; }
        public Nullable<System.Guid> CURRENCYGUID { get; set; }
        public Nullable<System.Guid> WAITERGUID { get; set; }
        public Nullable<System.Guid> CASHIERGUID { get; set; }
        public Nullable<System.Guid> ORDERTYPEGUID { get; set; }
        public Nullable<System.Guid> CATEGLISTGUID { get; set; }
        public Nullable<System.Guid> DISHGUID { get; set; }
        public string VOIDGUID { get; set; }
        public Nullable<System.DateTime> SHIFTDATE { get; set; }
        public Nullable<int> YEAR { get; set; }
        public Nullable<int> QUARTER { get; set; }
        public Nullable<int> MONTH { get; set; }
        public Nullable<int> WEEK { get; set; }
        public Nullable<int> DAY { get; set; }
        public Nullable<int> HOUR { get; set; }
        public Nullable<int> FIVEMINUTE { get; set; }
        public string RESTAURANT { get; set; }
        public string MIDSERVER { get; set; }
        public string CURRENCY { get; set; }
        public string WAITER { get; set; }
        public string CASHIER { get; set; }
        public string ORDERTYPE { get; set; }
        public string VOID { get; set; }
        public string DISH { get; set; }
        public Nullable<decimal> BASICSUM { get; set; }
        public Nullable<decimal> NATIONALSUM { get; set; }
        public Nullable<decimal> PRLISTSUM { get; set; }
        public Nullable<float> QUANTITY { get; set; }
    }
}
