//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAXDISHRULES
    {
        public int SIFR { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<int> TAXDISHTYPE { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public Nullable<int> CODE { get; set; }
        public Nullable<int> COT { get; set; }
        public Nullable<int> UOT { get; set; }
        public Nullable<short> STATUS { get; set; }
        public string RECSTAMP { get; set; }
    }
}
