//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPDELIVERYDATA
    {
        public int VISIT { get; set; }
        public int MIDSERVER { get; set; }
        public int ORDERIDENT { get; set; }
        public Nullable<int> RESTAURANTID { get; set; }
        public Nullable<System.DateTime> DELIVERYSTARTTIME { get; set; }
        public Nullable<System.DateTime> TRAVELTIME { get; set; }
        public Nullable<System.DateTime> DELIVERYTIME { get; set; }
        public Nullable<System.DateTime> DELIVERYREADYTIME { get; set; }
        public Nullable<int> ZONEID { get; set; }
        public string ZONENAME { get; set; }
        public Nullable<int> DELIVERYSTATE { get; set; }
        public string ORDERPREFIX { get; set; }
        public Nullable<System.DateTime> FORWARDERSENDTIME { get; set; }
        public Nullable<System.DateTime> FORWARDERRETURNTIME { get; set; }
        public Nullable<System.DateTime> REALDELIVERYTIME { get; set; }
        public Nullable<System.DateTime> DELIVERYLASTPROCESSTIME { get; set; }
        public Nullable<short> DELIVERYTAKEOUT { get; set; }
        public Nullable<System.DateTime> DELIVERYMINCOOKTIME { get; set; }
        public string GUIDSTRING { get; set; }
        public string TRANSACT_GUID { get; set; }
        public Nullable<int> TEMPDATAKIND { get; set; }
        public Nullable<int> TEMPDATASIGN { get; set; }
        public Nullable<int> TEMPSERVERID { get; set; }
    }
}
