//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPAWARDSPENALTIESDATA
    {
        public int VISIT { get; set; }
        public int MIDSERVER { get; set; }
        public int ORDERIDENT { get; set; }
        public int CHECKUNI { get; set; }
        public int UNI { get; set; }
        public Nullable<int> STATE { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public Nullable<int> OPERATOR { get; set; }
        public Nullable<int> MANAGER { get; set; }
        public Nullable<int> TYPEID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<short> CALCULATED { get; set; }
        public Nullable<int> ICOMMONSHIFT { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> CLOCKRECID { get; set; }
        public Nullable<decimal> FACTORVALUE { get; set; }
        public string TRANSACT_GUID { get; set; }
        public Nullable<int> TEMPDATAKIND { get; set; }
        public Nullable<int> TEMPDATASIGN { get; set; }
        public Nullable<int> TEMPSERVERID { get; set; }
    }
}
