//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPVISITGUESTS
    {
        public int VISIT { get; set; }
        public int MIDSERVER { get; set; }
        public int GUEST { get; set; }
        public string MNEMONIC { get; set; }
        public string CARDCODE { get; set; }
        public Nullable<int> INTFID { get; set; }
        public Nullable<long> MAXCREDITSUM { get; set; }
        public string HOLDER { get; set; }
        public Nullable<int> ENTRANCECARDTYPE { get; set; }
        public Nullable<long> CLIENTID { get; set; }
        public Nullable<long> ADDRESSID { get; set; }
        public string TRANSACT_GUID { get; set; }
        public Nullable<int> TEMPDATAKIND { get; set; }
        public Nullable<int> TEMPDATASIGN { get; set; }
        public Nullable<int> TEMPSERVERID { get; set; }
    }
}
