//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPGLOBALSHIFTS
    {
        public int MIDSERVER { get; set; }
        public int SHIFTNUM { get; set; }
        public string GUIDSTRING { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> CLOSETIME { get; set; }
        public Nullable<int> IMANAGER { get; set; }
        public Nullable<System.DateTime> SHIFTDATE { get; set; }
        public Nullable<short> CLOSED { get; set; }
        public Nullable<short> SENDED { get; set; }
        public Nullable<int> IBASICCURRENCY { get; set; }
        public Nullable<int> INATIONALCURRENCY { get; set; }
        public Nullable<int> IRESTAURANT { get; set; }
        public Nullable<System.DateTime> ORIGINALSHIFTDATE { get; set; }
        public Nullable<System.DateTime> SHIFTLOADDATETIME { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public string TRANSACT_GUID { get; set; }
        public Nullable<int> TEMPDATAKIND { get; set; }
        public Nullable<int> TEMPDATASIGN { get; set; }
        public Nullable<int> TEMPSERVERID { get; set; }
    }
}
