//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPGUESTREPLIES
    {
        public int MIDSERVER { get; set; }
        public int SIFR { get; set; }
        public Nullable<long> DATETIME { get; set; }
        public Nullable<int> OBJREFNO { get; set; }
        public Nullable<int> OBJIDENT { get; set; }
        public string GUESTCODE { get; set; }
        public Nullable<long> RATING { get; set; }
        public byte[] COMMENT { get; set; }
        public string TRANSACT_GUID { get; set; }
        public Nullable<int> TEMPDATAKIND { get; set; }
        public Nullable<int> TEMPDATASIGN { get; set; }
        public Nullable<int> TEMPSERVERID { get; set; }
    }
}
