//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CUBETEMP102
    {
        public int MIDSERVER { get; set; }
        public int VISIT { get; set; }
        public Nullable<int> DISHUNI { get; set; }
        public Nullable<System.DateTime> LOGICDATE { get; set; }
        public Nullable<int> SHIFT { get; set; }
        public Nullable<int> UOT { get; set; }
        public string UOTCODE { get; set; }
        public Nullable<int> COT { get; set; }
        public Nullable<int> COTCODE { get; set; }
        public Nullable<int> DISHIDENT { get; set; }
        public Nullable<int> MODIFIERIDENT { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<short> WEIGHT { get; set; }
        public Nullable<int> IRESTAURANT { get; set; }
        public string STATUS { get; set; }
    }
}
