//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CMCLSHIFTSDETAIL
    {
        public string ID { get; set; }
        public int MIDSERVER { get; set; }
        public Nullable<int> SHIFTID { get; set; }
        public int INOUTID { get; set; }
        public Nullable<int> CURRENCYID { get; set; }
        public string CASHID { get; set; }
        public string CASHNAME { get; set; }
        public Nullable<System.DateTime> OPENDT { get; set; }
        public string OPENDATE { get; set; }
        public string OPENTIME { get; set; }
        public Nullable<int> REASON { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<int> REASONSAFE { get; set; }
        public string RESTAURANTGUID { get; set; }
    }
}
