//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CUBEVIEW10927
    {
        public Nullable<System.DateTime> DATETIME { get; set; }
        public string COLLECTION { get; set; }
        public string CHANGENAME { get; set; }
        public int EMPLOYEESIFR { get; set; }
        public string EMPLOYEENAME { get; set; }
        public Nullable<int> ITEMSIFR { get; set; }
        public string ITEMNAME { get; set; }
        public string PROPNAME { get; set; }
        public string OLDVALUE { get; set; }
        public string NEWVALUE { get; set; }
        public int CHANGESCOUNT { get; set; }
    }
}
