//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CUBEVIEW10925
    {
        public int F00000002 { get; set; }
        public string DISH { get; set; }
        public string OPERATION { get; set; }
        public Nullable<System.DateTime> DATETIME___3 { get; set; }
        public string DATETIME_12 { get; set; }
        public Nullable<double> QNT { get; set; }
        public string TABLENAME { get; set; }
        public string TABLE { get; set; }
        public string WAITER { get; set; }
        public string ACCESS { get; set; }
        public string MANAGER { get; set; }
        public int SHIFTNUM { get; set; }
        public Nullable<System.DateTime> SHIFTDATE { get; set; }
        public string ORDERNAME { get; set; }
        public string NETNAME { get; set; }
        public Nullable<decimal> PAIDSUM { get; set; }
        public string RESTAURANTNAME { get; set; }
        public string MAKETSCHEMEDETAIL { get; set; }
        public Nullable<int> PARAMETER { get; set; }
        public Nullable<int> PRINTSHIFTNUM { get; set; }
        public string SOURCEORDER { get; set; }
        public string SOURCETABLE { get; set; }
        public Nullable<System.DateTime> REMINDAT { get; set; }
        public string STATUS { get; set; }
    }
}
