//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CUBEVIEW10948
    {
        public Nullable<int> code { get; set; }
        public string restaurant_name { get; set; }
        public string cashgroup_name { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int loaded1 { get; set; }
        public int loaded2 { get; set; }
        public Nullable<short> online { get; set; }
        public int flag { get; set; }
    }
}
