//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CUBEVIEW3001
    {
        public string WAITER { get; set; }
        public Nullable<int> CODE { get; set; }
        public string DISH { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public Nullable<decimal> PAYSUM { get; set; }
        public Nullable<decimal> PRLISTSUM { get; set; }
        public Nullable<short> EXCLUDEFROMEARNINGS { get; set; }
        public string ORDERCATEGORY { get; set; }
        public Nullable<int> CHECKNUM { get; set; }
        public int SHIFTNUM { get; set; }
        public Nullable<System.DateTime> PRINTAT___12 { get; set; }
        public Nullable<System.DateTime> SHIFTDATE { get; set; }
        public string CATEGPATH { get; set; }
        public string CLOSESTATION { get; set; }
        public string NETNAME { get; set; }
        public string CURRENCYTYPE { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<int> CURRENCYCODE { get; set; }
        public Nullable<int> SORTORDER { get; set; }
        public Nullable<int> CASHSHIFTNUM { get; set; }
        public string TABLE { get; set; }
        public string ORDERNAME { get; set; }
        public string CARDNUM { get; set; }
        public string OBJKIND { get; set; }
        public Nullable<decimal> TAXESADDED { get; set; }
        public string RESTAURANTNAME { get; set; }
        public string DISHCREATOR { get; set; }
        public string CATEGORY { get; set; }
        public string COMBODISH { get; set; }
        public Nullable<System.DateTime> CLOSEDATETIME___37 { get; set; }
        public string STATUS { get; set; }
        public string F00000036 { get; set; }
    }
}
