//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CMOPSHIFTS
    {
        public string ID { get; set; }
        public int MIDSERVER { get; set; }
        public int SHIFTID { get; set; }
        public Nullable<int> CURRENCYID { get; set; }
        public string CURRENCYNAME { get; set; }
        public Nullable<int> DRAWER { get; set; }
        public string CASHID { get; set; }
        public string CASHNAME { get; set; }
        public Nullable<int> CASHIERID { get; set; }
        public string CASHIERNAME { get; set; }
        public decimal CASHINOUTSSUM { get; set; }
        public Nullable<decimal> PAYMENTSSUM { get; set; }
        public string STARTDATE { get; set; }
        public string STARTTIME { get; set; }
        public string RESTAURANTGUID { get; set; }
    }
}
