//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CUBEVIEW1006
    {
        public string DELETEPERSON { get; set; }
        public Nullable<System.DateTime> SHIFTDATE { get; set; }
        public Nullable<decimal> NATIONALSUM { get; set; }
        public string CASHIER { get; set; }
        public string WAITER { get; set; }
        public int RECEIPTCOUNT { get; set; }
        public Nullable<int> CHECKNUM { get; set; }
        public string NETNAME { get; set; }
        public int SHIFTNUM { get; set; }
        public string REASON { get; set; }
        public string STATION { get; set; }
        public Nullable<int> CASHSHIFTNUM { get; set; }
        public string ORDERNAME { get; set; }
        public string RESTAURANTNAME { get; set; }
        public string STATUS { get; set; }
    }
}
