//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CUBEVIEW10943
    {
        public Nullable<System.DateTime> DATE { get; set; }
        public string DATENAME { get; set; }
        public Nullable<System.DateTime> DATETIMESTART { get; set; }
        public string TIME { get; set; }
        public string IAUTHOR { get; set; }
        public string CLOSESTATION { get; set; }
        public string RESTAURANTNAME { get; set; }
        public decimal PRLISTSUM { get; set; }
        public decimal DISCOUNTSUM { get; set; }
        public decimal BINDEDSUM { get; set; }
    }
}
