//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CUBEVIEW10937
    {
        public string DEP { get; set; }
        public Nullable<decimal> DISCSUM { get; set; }
        public int CHECKCOUNT { get; set; }
        public string DISCOUNT { get; set; }
        public string HOLDER { get; set; }
        public Nullable<int> CHECKNUM { get; set; }
        public string CARDCODE { get; set; }
        public Nullable<decimal> BINDEDSUM { get; set; }
        public Nullable<int> SHIFTNUM { get; set; }
        public Nullable<System.DateTime> SHIFTDATE { get; set; }
        public string NETNAME { get; set; }
        public string CURRENCY { get; set; }
        public string RESTAURANTNAME { get; set; }
        public int DISCOUNTVISIT { get; set; }
    }
}
