//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CUBEVIEW2007
    {
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<decimal> DURATION { get; set; }
        public Nullable<decimal> RIGHTDURATION { get; set; }
        public int STARTSHIFTNUM { get; set; }
        public string EMPLOYEE { get; set; }
        public string CARDCODE { get; set; }
        public string STARTSTATION { get; set; }
        public string ENDSTATION { get; set; }
        public Nullable<int> ENDSHIFTNUM { get; set; }
        public string STARTMANAGER { get; set; }
        public string ENDMANAGER { get; set; }
        public Nullable<short> AUTOENTRANCE { get; set; }
        public Nullable<short> NOENDINGLABEL { get; set; }
        public string ROLE { get; set; }
        public string NETNAME { get; set; }
        public Nullable<decimal> DELAY { get; set; }
        public Nullable<short> LATENESS { get; set; }
        public Nullable<System.DateTime> SHIFTSTARTTIME { get; set; }
        public string MAXSHIFTDURATION_12 { get; set; }
        public string SHIFTDURATION_12 { get; set; }
        public Nullable<System.DateTime> SHIFTDATE { get; set; }
        public string RESTAURANTNAME { get; set; }
        public string STATUS { get; set; }
    }
}
