//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Dlv_qryDeliveryGetOrderList {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class RK7CMD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] extSourceField;
        
        private string[] notExtSourceField;
        
        private string cMDField;
        
        private string lastversionField;
        
        public RK7CMD() {
            this.cMDField = "DeliveryGetOrderList";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExtSource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
        public string[] ExtSource {
            get {
                return this.extSourceField;
            }
            set {
                this.extSourceField = value;
                this.RaisePropertyChanged("ExtSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NotExtSource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger")]
        public string[] NotExtSource {
            get {
                return this.notExtSourceField;
            }
            set {
                this.notExtSourceField = value;
                this.RaisePropertyChanged("NotExtSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CMD {
            get {
                return this.cMDField;
            }
            set {
                this.cMDField = value;
                this.RaisePropertyChanged("CMD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string lastversion {
            get {
                return this.lastversionField;
            }
            set {
                this.lastversionField = value;
                this.RaisePropertyChanged("lastversion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
