//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Dlv_resDeliveryGetOrderList {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("RK7QueryResult", Namespace="", IsNullable=false)]
    public partial class RK7QueryResult1 : RK7QueryResult {
        
        private RK7QueryResultExtraInfo extraInfoField;
        
        private RK7QueryResultOrder[] orderField;
        
        private string lastversionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RK7QueryResultExtraInfo ExtraInfo {
            get {
                return this.extraInfoField;
            }
            set {
                this.extraInfoField = value;
                this.RaisePropertyChanged("ExtraInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Order", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RK7QueryResultOrder[] Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
                this.RaisePropertyChanged("Order");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string lastversion {
            get {
                return this.lastversionField;
            }
            set {
                this.lastversionField = value;
                this.RaisePropertyChanged("lastversion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RK7QueryResultExtraInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool restaurantStateField;
        
        private bool restaurantStateFieldSpecified;
        
        private System.DateTime restaurantTimeField;
        
        private bool restaurantTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool restaurantState {
            get {
                return this.restaurantStateField;
            }
            set {
                this.restaurantStateField = value;
                this.RaisePropertyChanged("restaurantState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool restaurantStateSpecified {
            get {
                return this.restaurantStateFieldSpecified;
            }
            set {
                this.restaurantStateFieldSpecified = value;
                this.RaisePropertyChanged("restaurantStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime restaurantTime {
            get {
                return this.restaurantTimeField;
            }
            set {
                this.restaurantTimeField = value;
                this.RaisePropertyChanged("restaurantTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool restaurantTimeSpecified {
            get {
                return this.restaurantTimeFieldSpecified;
            }
            set {
                this.restaurantTimeFieldSpecified = value;
                this.RaisePropertyChanged("restaurantTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resEmployeeItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class resRefItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class resEmployeeItem : resRefItem {
        
        private resRefItem roleField;
        
        /// <remarks/>
        public resRefItem Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deliveryBlock : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int deliveryStateField;
        
        private bool deliveryStateFieldSpecified;
        
        private System.DateTime startTimeField;
        
        private bool startTimeFieldSpecified;
        
        private System.DateTime travelTimeField;
        
        private bool travelTimeFieldSpecified;
        
        private System.DateTime deliveryTimeField;
        
        private bool deliveryTimeFieldSpecified;
        
        private System.DateTime forwarderSendTimeField;
        
        private bool forwarderSendTimeFieldSpecified;
        
        private System.DateTime forwarderReturnTimeField;
        
        private bool forwarderReturnTimeFieldSpecified;
        
        private System.DateTime realDeliveryTimeField;
        
        private bool realDeliveryTimeFieldSpecified;
        
        private System.DateTime lastProcessTimeField;
        
        private bool lastProcessTimeFieldSpecified;
        
        private System.DateTime minCookTimeField;
        
        private bool minCookTimeFieldSpecified;
        
        private int zoneIDField;
        
        private bool zoneIDFieldSpecified;
        
        private string zoneNameField;
        
        private string orderPrefixField;
        
        private bool isTakeOutField;
        
        private bool isTakeOutFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int deliveryState {
            get {
                return this.deliveryStateField;
            }
            set {
                this.deliveryStateField = value;
                this.RaisePropertyChanged("deliveryState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveryStateSpecified {
            get {
                return this.deliveryStateFieldSpecified;
            }
            set {
                this.deliveryStateFieldSpecified = value;
                this.RaisePropertyChanged("deliveryStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
                this.RaisePropertyChanged("startTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startTimeSpecified {
            get {
                return this.startTimeFieldSpecified;
            }
            set {
                this.startTimeFieldSpecified = value;
                this.RaisePropertyChanged("startTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime travelTime {
            get {
                return this.travelTimeField;
            }
            set {
                this.travelTimeField = value;
                this.RaisePropertyChanged("travelTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool travelTimeSpecified {
            get {
                return this.travelTimeFieldSpecified;
            }
            set {
                this.travelTimeFieldSpecified = value;
                this.RaisePropertyChanged("travelTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime deliveryTime {
            get {
                return this.deliveryTimeField;
            }
            set {
                this.deliveryTimeField = value;
                this.RaisePropertyChanged("deliveryTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveryTimeSpecified {
            get {
                return this.deliveryTimeFieldSpecified;
            }
            set {
                this.deliveryTimeFieldSpecified = value;
                this.RaisePropertyChanged("deliveryTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime forwarderSendTime {
            get {
                return this.forwarderSendTimeField;
            }
            set {
                this.forwarderSendTimeField = value;
                this.RaisePropertyChanged("forwarderSendTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forwarderSendTimeSpecified {
            get {
                return this.forwarderSendTimeFieldSpecified;
            }
            set {
                this.forwarderSendTimeFieldSpecified = value;
                this.RaisePropertyChanged("forwarderSendTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime forwarderReturnTime {
            get {
                return this.forwarderReturnTimeField;
            }
            set {
                this.forwarderReturnTimeField = value;
                this.RaisePropertyChanged("forwarderReturnTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forwarderReturnTimeSpecified {
            get {
                return this.forwarderReturnTimeFieldSpecified;
            }
            set {
                this.forwarderReturnTimeFieldSpecified = value;
                this.RaisePropertyChanged("forwarderReturnTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime realDeliveryTime {
            get {
                return this.realDeliveryTimeField;
            }
            set {
                this.realDeliveryTimeField = value;
                this.RaisePropertyChanged("realDeliveryTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool realDeliveryTimeSpecified {
            get {
                return this.realDeliveryTimeFieldSpecified;
            }
            set {
                this.realDeliveryTimeFieldSpecified = value;
                this.RaisePropertyChanged("realDeliveryTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime lastProcessTime {
            get {
                return this.lastProcessTimeField;
            }
            set {
                this.lastProcessTimeField = value;
                this.RaisePropertyChanged("lastProcessTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastProcessTimeSpecified {
            get {
                return this.lastProcessTimeFieldSpecified;
            }
            set {
                this.lastProcessTimeFieldSpecified = value;
                this.RaisePropertyChanged("lastProcessTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime minCookTime {
            get {
                return this.minCookTimeField;
            }
            set {
                this.minCookTimeField = value;
                this.RaisePropertyChanged("minCookTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minCookTimeSpecified {
            get {
                return this.minCookTimeFieldSpecified;
            }
            set {
                this.minCookTimeFieldSpecified = value;
                this.RaisePropertyChanged("minCookTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int zoneID {
            get {
                return this.zoneIDField;
            }
            set {
                this.zoneIDField = value;
                this.RaisePropertyChanged("zoneID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zoneIDSpecified {
            get {
                return this.zoneIDFieldSpecified;
            }
            set {
                this.zoneIDFieldSpecified = value;
                this.RaisePropertyChanged("zoneIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string zoneName {
            get {
                return this.zoneNameField;
            }
            set {
                this.zoneNameField = value;
                this.RaisePropertyChanged("zoneName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string orderPrefix {
            get {
                return this.orderPrefixField;
            }
            set {
                this.orderPrefixField = value;
                this.RaisePropertyChanged("orderPrefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isTakeOut {
            get {
                return this.isTakeOutField;
            }
            set {
                this.isTakeOutField = value;
                this.RaisePropertyChanged("isTakeOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isTakeOutSpecified {
            get {
                return this.isTakeOutFieldSpecified;
            }
            set {
                this.isTakeOutFieldSpecified = value;
                this.RaisePropertyChanged("isTakeOutSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RK7QueryResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverVersionField;
        
        private string xmlVersionField;
        
        private string netNameField;
        
        private string cMDField;
        
        private RK7QueryResultStatus statusField;
        
        private string rK7ErrorNField;
        
        private string errorTextField;
        
        private string workTimeField;
        
        private System.DateTime dateTimeField;
        
        private string processedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string ServerVersion {
            get {
                return this.serverVersionField;
            }
            set {
                this.serverVersionField = value;
                this.RaisePropertyChanged("ServerVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string XmlVersion {
            get {
                return this.xmlVersionField;
            }
            set {
                this.xmlVersionField = value;
                this.RaisePropertyChanged("XmlVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NetName {
            get {
                return this.netNameField;
            }
            set {
                this.netNameField = value;
                this.RaisePropertyChanged("NetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string CMD {
            get {
                return this.cMDField;
            }
            set {
                this.cMDField = value;
                this.RaisePropertyChanged("CMD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RK7QueryResultStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string RK7ErrorN {
            get {
                return this.rK7ErrorNField;
            }
            set {
                this.rK7ErrorNField = value;
                this.RaisePropertyChanged("RK7ErrorN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
                this.RaisePropertyChanged("ErrorText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string WorkTime {
            get {
                return this.workTimeField;
            }
            set {
                this.workTimeField = value;
                this.RaisePropertyChanged("WorkTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
                this.RaisePropertyChanged("DateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string Processed {
            get {
                return this.processedField;
            }
            set {
                this.processedField = value;
                this.RaisePropertyChanged("Processed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum RK7QueryResultStatus {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No changes")]
        Nochanges,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Execution Started")]
        ExecutionStarted,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Query Parse Error")]
        QueryParseError,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Bad Query Parameters")]
        BadQueryParameters,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Query Executing Error")]
        QueryExecutingError,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Result Writing Error")]
        ResultWritingError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RK7QueryResultOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RK7QueryResultOrderExtSource[] extSourceField;
        
        private deliveryBlock deliveryBlockField;
        
        private resRefItem mainWaiterField;
        
        private resRefItem creatorField;
        
        private resRefItem restaurantField;
        
        private string orderIdentField;
        
        private string versionField;
        
        private int crc32Field;
        
        private string guidField;
        
        private string orderNameField;
        
        private System.DateTime createTimeField;
        
        private bool createTimeFieldSpecified;
        
        private System.DateTime lastChangeTimeField;
        
        private bool lastChangeTimeFieldSpecified;
        
        private string totalPiecesField;
        
        private string prepaySumField;
        
        private string promisedSumField;
        
        private bool deletedField;
        
        private bool deletedFieldSpecified;
        
        private bool startedField;
        
        private bool startedFieldSpecified;
        
        private bool readyField;
        
        private bool readyFieldSpecified;
        
        private bool paidField;
        
        private bool paidFieldSpecified;
        
        private int orderSumField;
        
        private bool orderSumFieldSpecified;
        
        private long clientIDField;
        
        private bool clientIDFieldSpecified;
        
        private long addressIDField;
        
        private bool addressIDFieldSpecified;
        
        public RK7QueryResultOrder() {
            this.prepaySumField = "0";
            this.promisedSumField = "0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExtSource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RK7QueryResultOrderExtSource[] ExtSource {
            get {
                return this.extSourceField;
            }
            set {
                this.extSourceField = value;
                this.RaisePropertyChanged("ExtSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public deliveryBlock DeliveryBlock {
            get {
                return this.deliveryBlockField;
            }
            set {
                this.deliveryBlockField = value;
                this.RaisePropertyChanged("DeliveryBlock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resRefItem MainWaiter {
            get {
                return this.mainWaiterField;
            }
            set {
                this.mainWaiterField = value;
                this.RaisePropertyChanged("MainWaiter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resRefItem Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
                this.RaisePropertyChanged("Creator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resRefItem Restaurant {
            get {
                return this.restaurantField;
            }
            set {
                this.restaurantField = value;
                this.RaisePropertyChanged("Restaurant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string orderIdent {
            get {
                return this.orderIdentField;
            }
            set {
                this.orderIdentField = value;
                this.RaisePropertyChanged("orderIdent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int crc32 {
            get {
                return this.crc32Field;
            }
            set {
                this.crc32Field = value;
                this.RaisePropertyChanged("crc32");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
                this.RaisePropertyChanged("guid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string orderName {
            get {
                return this.orderNameField;
            }
            set {
                this.orderNameField = value;
                this.RaisePropertyChanged("orderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime createTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("createTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createTimeSpecified {
            get {
                return this.createTimeFieldSpecified;
            }
            set {
                this.createTimeFieldSpecified = value;
                this.RaisePropertyChanged("createTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime lastChangeTime {
            get {
                return this.lastChangeTimeField;
            }
            set {
                this.lastChangeTimeField = value;
                this.RaisePropertyChanged("lastChangeTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastChangeTimeSpecified {
            get {
                return this.lastChangeTimeFieldSpecified;
            }
            set {
                this.lastChangeTimeFieldSpecified = value;
                this.RaisePropertyChanged("lastChangeTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string totalPieces {
            get {
                return this.totalPiecesField;
            }
            set {
                this.totalPiecesField = value;
                this.RaisePropertyChanged("totalPieces");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string prepaySum {
            get {
                return this.prepaySumField;
            }
            set {
                this.prepaySumField = value;
                this.RaisePropertyChanged("prepaySum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string promisedSum {
            get {
                return this.promisedSumField;
            }
            set {
                this.promisedSumField = value;
                this.RaisePropertyChanged("promisedSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deletedSpecified {
            get {
                return this.deletedFieldSpecified;
            }
            set {
                this.deletedFieldSpecified = value;
                this.RaisePropertyChanged("deletedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool started {
            get {
                return this.startedField;
            }
            set {
                this.startedField = value;
                this.RaisePropertyChanged("started");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startedSpecified {
            get {
                return this.startedFieldSpecified;
            }
            set {
                this.startedFieldSpecified = value;
                this.RaisePropertyChanged("startedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ready {
            get {
                return this.readyField;
            }
            set {
                this.readyField = value;
                this.RaisePropertyChanged("ready");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readySpecified {
            get {
                return this.readyFieldSpecified;
            }
            set {
                this.readyFieldSpecified = value;
                this.RaisePropertyChanged("readySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool paid {
            get {
                return this.paidField;
            }
            set {
                this.paidField = value;
                this.RaisePropertyChanged("paid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paidSpecified {
            get {
                return this.paidFieldSpecified;
            }
            set {
                this.paidFieldSpecified = value;
                this.RaisePropertyChanged("paidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int orderSum {
            get {
                return this.orderSumField;
            }
            set {
                this.orderSumField = value;
                this.RaisePropertyChanged("orderSum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderSumSpecified {
            get {
                return this.orderSumFieldSpecified;
            }
            set {
                this.orderSumFieldSpecified = value;
                this.RaisePropertyChanged("orderSumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long clientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
                this.RaisePropertyChanged("clientID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clientIDSpecified {
            get {
                return this.clientIDFieldSpecified;
            }
            set {
                this.clientIDFieldSpecified = value;
                this.RaisePropertyChanged("clientIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long addressID {
            get {
                return this.addressIDField;
            }
            set {
                this.addressIDField = value;
                this.RaisePropertyChanged("addressID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addressIDSpecified {
            get {
                return this.addressIDFieldSpecified;
            }
            set {
                this.addressIDFieldSpecified = value;
                this.RaisePropertyChanged("addressIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RK7QueryResultOrderExtSource : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceField;
        
        private string extIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extID {
            get {
                return this.extIDField;
            }
            set {
                this.extIDField = value;
                this.RaisePropertyChanged("extID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
