//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Models.SKK
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleBlockAccess
    {
        public int id { get; set; }
        public int block_id { get; set; }
        public int restaurant_id { get; set; }
    
        public virtual ArticleBlock ArticleBlock { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
